# Site settings
title: Welcome
header-img: img/musee_dauphinois.jpg
email: alejandro.blumentals@gmail.com
copyright_name: Alejandro Blumentals
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
github_username:  blumenta
email_username:  alejandro.blumentals@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
use_math: true
future: true
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

#gems: [jekyll-paginate, jekyll-feed]

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge